# Sidebar navigation

- label: 'Начало работы'
  items:
    - label: 'Логика работы'
      link: '/started/logic'
    - label: 'Установка'
      link: '/started/install'
    - label: 'Авторизация'
      link: '/started/auth'
    - label: 'Дашбоард'
      link: '/started/dashboard'
    - label: 'Статистика'
      link: '/started/statistick'
    - label: 'Офферы'
      link: '/started/offers'
    - label: 'Настройка'
      link: '/started/settings'
- label: 'Настройки'
  items:
    - label: 'Настройка группы'
      link: '/settings/groups'
    - label: 'Настройка потока'
      link: '/settings/streams'
    - label: 'Настройка фильтрации'
      link: '/settings/filters'
- label: 'Редиректы'
  items:
    - label: 'Http redirect'
      link: '/redirects/http'
    - label: 'JS redirect'
      link: '/redirects/js'
    - label: 'Offer'
      link: '/redirects/offer'
    - label: 'JS Selection'
      link: '/redirects/jsSelection'
    - label: 'Remote'
      link: '/redirects/remote'
    - label: 'Iframe'
      link: '/redirects/iframe'
    - label: 'Iframe Redirect'
      link: '/redirects/iframeRedirect'
    - label: 'Meta Redirect'
      link: '/redirects/meta'
    - label: 'JavaScript'
      link: '/redirects/javascript'
    - label: 'Остальные'
      link: '/redirects/other'
- label: 'Дополнительно'
  items:
    - label: 'Помощь проекту'
      link: '/extra/help'
    - label: 'Постбеки'
      link: '/extra/postbacks'
    - label: 'FAQ'
      link: '/extra/faq'
    - label: 'Changlog'
      link: '/extra/changelog'
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/dengivseti/while_tracker
    - label: 'Группа в телеграм'
      link: https://t.me/WhileTracker